
 
 
ALTER DATABASE intereu6_ffproxy DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE proxy DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE proxy CHANGE cn_country cn_country VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;

ALTER TABLE proxy CHANGE cn_city cn_city VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;